apiVersion: v1
kind: Secret
metadata:
  name: temporal-sql-secrets
  namespace: temporal
type: Opaque
stringData:
  # Adjust user/password/db names to what you’ve created
  SQL_DEFAULT_DSN:      postgresql://temporal:temporalpass@pg-ha-pgpool.postgres-temporal.svc.cluster.local:5432/temporal?sslmode=disable
  SQL_VISIBILITY_DSN:  postgresql://temporal:temporalpass@pg-ha-pgpool.postgres-temporal.svc.cluster.local:5432/temporal_visibility?sslmode=disable
