# temporal/secrets/temporal-sql-secrets-admin.yaml
apiVersion: v1
kind: Secret
metadata:
  name: temporal-sql-secrets-admin
  namespace: temporal
type: Opaque
stringData:
  default.sql.dsn:    "postgres://postgres:<SUPERPASS>@temporal-pg-rw.postgres-temporal.svc.cluster.local:5432/temporal?sslmode=disable"
  visibility.sql.dsn: "postgres://postgres:<SUPERPASS>@temporal-pg-rw.postgres-temporal.svc.cluster.local:5432/temporal_visibility?sslmode=disable"
