apiVersion: v1
kind: Secret
metadata:
  name: temporal-db-auth
  namespace: postgres-temporal
type: kubernetes.io/basic-auth
stringData:
  username: temporal
  password: temporalPass123

---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-visibility-auth
  namespace: postgres-temporal
type: kubernetes.io/basic-auth
stringData:
  username: visibility
  password: visibilityPass123
