# FINAL values.yaml for bitnami/postgresql-ha

# If you want to use Docker Hub images, leave this as docker.io.
# If you want **your private ECR**, use per-image overrides below section “Use ECR”.
global:
  imageRegistry: docker.io

fullnameOverride: pg-ha

pgpool:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/pgpool
    # DO NOT set tag unless you know it exists. Let the chart pick a valid tag.
    pullPolicy: IfNotPresent
  replicaCount: 1
  # Keep pgpool off Fargate
  nodeSelector:
    kubernetes.io/arch: amd64
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values: ["fargate"]

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql-repmgr
    # DO NOT set tag unless you know it exists. Let the chart pick a valid tag.
    pullPolicy: IfNotPresent

  replicaCount: 2
  # Order pods so EBS can attach predictably
  podManagementPolicy: OrderedReady

  # Keep DB off Fargate
  nodeSelector:
    kubernetes.io/arch: amd64
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values: ["fargate"]

  # Use default StorageClass (EBS-CSI with WaitForFirstConsumer recommended)
  persistence:
    enabled: true
    size: 10Gi
    # storageClass: ""  # leave empty to use cluster default

  # Ensure we are NOT referencing a non-existent initdb scripts CM
  initdbScriptsCM: ""
  configurationCM: ""

service:
  type: ClusterIP

# ---------- If you pull from your **private ECR** instead ----------
# Uncomment and adjust ONLY if you mirrored the **exact** tags there.
# Also add imagePullSecrets (see section 5).
#
# pgpool:
#   image:
#     registry: 856517911253.dkr.ecr.ap-southeast-1.amazonaws.com
#     repository: dockerhubio/bitnami/pgpool
#     tag: 4.5.4-debian-12-r0   # must exist in your ECR
#   imagePullSecrets:
#     - name: ecr-pull
#
# postgresql:
#   image:
#     registry: 856517911253.dkr.ecr.ap-southeast-1.amazonaws.com
#     repository: dockerhubio/bitnami/postgresql-repmgr
#     tag: 16-debian-12         # must exist in your ECR
#   imagePullSecrets:
#     - name: ecr-pull

