nameOverride: temporal-ha
fullnameOverride: temporal-ha

prometheus:
  enabled: true
grafana:
  enabled: false

server:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  envFrom:
    - secretRef:
        name: temporal-sql-secrets

  # Force Helm config, not docker.yaml
  additionalEnv:
    - name: TEMPORAL_ENV
      value: "kubernetes"
    - name: TEMPORAL_CONFIG_DIR
      value: "/etc/temporal/config"
  additionalArgs:
    - "--env"
    - "kubernetes"
    - "--config"
    - "/etc/temporal/config/config.yaml"

  config:
    persistence:
      default:
        driver: sql
        sql:
          driver: postgres12
          dsn: ${SQL_DEFAULT_DSN}
          maxConns: 40
          maxConnLifetime: 1h
      visibility:
        driver: sql
        sql:
          driver: postgres12
          dsn: ${SQL_VISIBILITY_DSN}
          maxConns: 40
          maxConnLifetime: 1h

web:
  replicaCount: 2
  service:
    type: ClusterIP

cassandra:
  enabled: false
elasticsearch:
  enabled: false
mysql:
  enabled: false

schema:
  createDatabase:
    enabled: false
  setup:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets
  update:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets
