nameOverride: temporal-ha
fullnameOverride: temporal-ha

prometheus:
  enabled: true
grafana:
  enabled: false

server:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  # DSNs from secret
  envFrom:
    - secretRef:
        name: temporal-sql-secrets

  # Force Helm config path; avoid docker defaults entirely
  additionalEnv:
    - name: TEMPORAL_ENV
      value: "kubernetes"
    - name: TEMPORAL_CONFIG_DIR
      value: "/etc/temporal/config"
    - name: TEMPORAL_CONFIG_FILE
      value: "/etc/temporal/config/config_template.yaml"
  additionalArgs:
    - "--env"
    - "kubernetes"
    - "--config"
    - "/etc/temporal/config/config_template.yaml"
    - "--allow-no-auth"

  # DSN-only with the correct driver name (postgres12!)
  config:
    persistence:
      default:
        driver: sql
        sql:
          driver: postgres12
          dsn: ${SQL_DEFAULT_DSN}
          maxConns: 20
          maxConnLifetime: 1h
      visibility:
        driver: sql
        sql:
          driver: postgres12
          dsn: ${SQL_VISIBILITY_DSN}
          maxConns: 20
          maxConnLifetime: 1h

web:
  replicaCount: 2
  service:
    type: ClusterIP

# Disable other backends
cassandra:
  enabled: false
elasticsearch:
  enabled: false
mysql:
  enabled: false

# Run schema jobs so Temporal tables get created/updated
schema:
  createDatabase:
    enabled: false
  setup:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets
  update:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets
