apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster-dev
  namespace: argocd
spec:
  project: default
  destination:
    name: eks-gitops-bridge
    namespace: postgres-temporal
  source:
    repoURL: https://github.com/<your-org>/<your-repo>.git
    targetRevision: main
    path: cnpg/cluster-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
