apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-ha-dev1
  namespace: argocd
spec:
  project: default

  destination:
    name: eks-gitops-bridge
    namespace: temporal

  source:
    repoURL: https://github.com/Pradeepbisht1/temporal-gitops-demo.git
    path: temporal/charts/temporal-stack
    targetRevision: HEAD
    # NOTE: Keep your Postgres/Cassandra-off settings inside
    # temporal/charts/temporal-stack/values.yaml in the repo.

  # Stop Argo from trying to mutate bound PVC specs (immutable)
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jqPathExpressions:
        - ".spec.storageClassName"
        - ".spec.volumeName"
        - ".spec.selector"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      # DO NOT add Replace=true (it causes Job/PVC errors)
