apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: temporal-pg
  namespace: postgres-temporal
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    # storageClass: gp3  # set if your default isn't what you want

  enableSuperuserAccess: true
  superuserSecret:
    name: temporal-pg-superuser

  bootstrap:
    initdb:
      dataChecksums: true
      encoding: "UTF8"
      localeCType: "en_US.UTF-8"
      localeCollate: "en_US.UTF-8"

  monitoring:
    enablePodMonitor: false

  tolerations:
    - key: "karpenter.sh/disrupted"
      operator: "Exists"
      effect: "NoSchedule"

  affinity:
    podAntiAffinityType: preferred
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: In
                values: ["ec2"]

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
