apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: temporal-pg
  namespace: postgres-temporal
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi

  enableSuperuserAccess: true
  superuserSecret:
    name: temporal-pg-superuser

  bootstrap:
    initdb:
      dataChecksums: true
      encoding: "UTF8"
      localeCType: "en_US.UTF-8"
      localeCollate: "en_US.UTF-8"
      # NOTE: We keep DB/user creation outside to avoid cleartext in manifest.
      # We'll create DBs via Temporal schema jobs or the job below.

  monitoring:
    enablePodMonitor: false

  # Anti-fargate example (keep if needed for your cluster)
  nodeMaintenanceWindow: {}
  affinity:
    podAntiAffinityType: preferred
    tolerations: []
    nodeSelector:
      eks.amazonaws.com/compute-type: "ec2"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  # Services:
  # - temporal-pg-rw.postgres-temporal.svc.cluster.local (primary RW)
  # - temporal-pg-ro.postgres-temporal.svc.cluster.local (read-only)
