# ---------- TURN OFF BACKENDS YOU DON'T USE ----------
cassandra:
  enabled: false

elasticsearch:
  enabled: false

mysql:
  enabled: false

# ---------- TEMPORAL SERVER (Postgres via CNPG) ----------
server:
  # Per-service replicas (integers, not quoted)
  replicas:
    frontend: 2
    history: 2
    matching: 2
    worker: 2

  image:
    repository: temporalio/server
    tag: "1.28.1"
    pullPolicy: IfNotPresent

  config:
    logLevel: info
    numHistoryShards: 512
    persistence:
      # DEFAULT STORE
      default:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-pg-rw.postgres-temporal.svc
          port: 5432
          database: temporal
          existingSecret: temporal-ha-dev1-default-store   # must exist; keys below
          userKey: username
          passwordKey: password

      # VISIBILITY STORE
      visibility:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-pg-rw.postgres-temporal.svc
          port: 5432
          database: temporal_visibility
          existingSecret: temporal-ha-dev1-visibility-store # must exist; keys below
          userKey: username
          passwordKey: password

# ---------- WEB ----------
web:
  enabled: true
  replicaCount: 1
  image:
    repository: temporalio/ui
    tag: "2.39.0"
    pullPolicy: IfNotPresent

# ---------- SCHEMA JOBS ----------
# If you ever see "Job ... field is immutable", bump jobNameSuffix (e.g., -recreate5)
schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
    backoffLimit: 100
  update:
    enabled: true
    backoffLimit: 100
  jobNameSuffix: "-recreate4"

# ---------- MONITORING (bind to the existing Prometheus PVC) ----------
prometheus:
  enabled: true
  server:
    replicaCount: 1
    persistentVolume:
      enabled: true
      existingClaim: temporal-ha-dev1-prometheus-server
      # Do NOT set size/storageClass/volumeName when using existingClaim
  pushgateway:
    enabled: true
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: true

# ---------- GRAFANA ----------
grafana:
  enabled: true
  replicas: 1
