# temporal/charts/temporal-stack/values.yaml
temporal:
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false

  server:
    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12           # use "postgres12" for Temporal chart
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            existingSecret: temporal-sql-secrets   # chart will read key "password" from this secret
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            existingSecret: temporal-sql-secrets

    # keep your CA mount if/when you move to TLS; with sslmode=disable it's not used
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    # Schema Jobs as Argo hooks (we’ll tweak deletion policy below)
    schema:
      setup:
        enabled: true
        existingSecret: temporal-sql-secrets-admin
        existingSecretKey: default.sql.dsn   # this key is fine for the schema job (it uses DSN)
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
          argocd.argoproj.io/sync-wave: "-1"
      update:
        enabled: true
        existingSecret: temporal-sql-secrets-admin
        existingSecretKey: default.sql.dsn
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
          argocd.argoproj.io/sync-wave: "-1"
