temporal:
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false
  mysql:
    enabled: false

  server:
    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            dsn: ${SQL_DEFAULT_DSN}
            maxConns: 20
            maxConnLifetime: 1h
        visibility:
          driver: sql
          sql:
            driver: postgres12
            dsn: ${SQL_VISIBILITY_DSN}
            maxConns: 20
            maxConnLifetime: 1h

    # 🔒 hard-pin process startup flags via command/args
    command: ["temporal-server"]
    args:
      - start
      - --env
      - kubernetes
      - --config
      - /etc/temporal/config/config_template.yaml

    # env for consistency (ok if template ignores these)
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config
      - name: SQL_DEFAULT_DSN
        valueFrom:
          secretKeyRef:
            name: temporal-sql-secrets
            key: default.sql.dsn
      - name: SQL_VISIBILITY_DSN
        valueFrom:
          secretKeyRef:
            name: temporal-sql-secrets
            key: visibility.sql.dsn

  # (Optional) also pin per service, in case your chart launches them separately
  frontend:
    command: ["temporal-server"]
    args: ["start","--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  history:
    command: ["temporal-server"]
    args: ["start","--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  matching:
    command: ["temporal-server"]
    args: ["start","--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  worker:
    command: ["temporal-server"]
    args: ["start","--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

prometheus:
  nodeExporter:
    enabled: false
