# --- DISABLE Cassandra & ES paths ---
cassandra:
  enabled: false

elasticsearch:
  enabled: false
  # agar sirf SQL visibility chahte ho to ES na chalao

# --- PERSISTENCE: SQL (Postgres) ---
server:
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres"
          # dsn ko env se lenge (secret se)
          # dsn: ${SQL_DEFAULT_DSN}
      visibility:
        driver: "sql"
        sql:
          driver: "postgres"
          # dsn: ${SQL_VISIBILITY_DSN}

# --- SCHEMA JOBS: run for SQL ---
schema:
  createDatabase:
    enabled: true          # visibility DB create karwayega
    envFrom:
      - secretRef:
          name: temporal-sql-secrets-admin   # superuser DSN (postgres)
  setup:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets         # app user DSN (temporal)
  update:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets

# (Optional) Prometheus node exporter taints fix
prometheus:
  nodeExporter:
    tolerations:
      - operator: "Exists"
