temporal:
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false

  server:
    image:
      repository: temporalio/server
      tag: "1.28.1"

    # optional, silence warning
    extraArgs:
      - --allow-no-auth

    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            existingSecret: temporal-sql-secrets    # key: password
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            existingSecret: temporal-sql-secrets    # key: password

    # (optional; only used if you enable TLS to PG later)
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    schema:
      image:
        repository: temporalio/admin-tools
        tag: "1.28"   # valid tag; avoid 1.28.0 & 1.28.1 if your registry doesn’t have them

      setup:
        enabled: true
        datastores:
          default:
            existingSecret: temporal-sql-secrets-admin-override
            existingSecretKey: default.sql.dsn
          visibility:
            existingSecret: temporal-sql-secrets-admin-override
            existingSecretKey: visibility.sql.dsn
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed
          argocd.argoproj.io/sync-wave: "-1"

      update:
        enabled: true
        datastores:
          default:
            existingSecret: temporal-sql-secrets-admin-override
            existingSecretKey: default.sql.dsn
          visibility:
            existingSecret: temporal-sql-secrets-admin-override
            existingSecretKey: visibility.sql.dsn
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed
          argocd.argoproj.io/sync-wave: "-1"

      createNamespace:
        enabled: true
        namespace: default
        retention: 7d
