temporal:
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false

  server:
    image:
      repository: temporalio/server
      tag: "1.28.1"

    # Dev only: silence auth warning
    extraArgs:
      - --allow-no-auth

    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            existingSecret: temporal-sql-secrets   # key must be: password
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            existingSecret: temporal-sql-secrets   # key must be: password

    # Optional TLS mounts (safe to keep even if not used yet)
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    # ---- Disable all schema jobs (the main kill switch) ----
    schema:
      enabled: false
      image:
        repository: temporalio/admin-tools
        tag: "1.28"
      createDatabase:
        enabled: false
      setup:
        enabled: false
      update:
        enabled: false
      # Also disable namespace creation job
      createNamespace:
        enabled: false
        namespace: default
        retention: 7d

# ---- Monitoring toggles must be TOP-LEVEL (siblings of `temporal`) ----
grafana:
  enabled: false

prometheus:
  enabled: false
  server:
    enabled: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false

