temporal:
  cassandra:
    enabled: false

  elasticsearch:
    enabled: false

  server:
    image:
      repository: temporalio/server
      tag: "1.28.1"
    extraArgs:
      - --allow-no-auth

    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            existingSecret: temporal-sql-secrets   # key: password
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            existingSecret: temporal-sql-secrets   # key: password

    # Optional (TLS to Postgres later)
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    schema:
      image:
        repository: temporalio/admin-tools
        tag: "1.28"

      # TURN OFF all built-in schema jobs
      enabled: false               # <- belts & suspenders
      createDatabase: { enabled: false }
      setup:          { enabled: false }
      update:         { enabled: false }

      # If you still want auto-create namespace, flip this to true.
      createNamespace:
        enabled: true
        namespace: default
        retention: 7d

# ---------- MONITORING STACK (root-level) ----------
grafana:
  enabled: false

prometheus:
  enabled: false
  server:
    enabled: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
