# --- temporal/charts/temporal-stack/values.yaml ---

# Values for the wrapper "temporal-stack" chart
# All Temporal chart overrides must live under the "temporal:" key (the dependency's name).

# --- Temporal subchart overrides (IMPORTANT: nested) ---
temporal:
  nameOverride: temporal-ha
  fullnameOverride: temporal-ha

  # Disable non-SQL backends
  cassandra:
    enabled: false

  elasticsearch:
    enabled: false

  mysql:
    enabled: false

  server:
    replicaCount: 3
    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    # Load application DSNs from the normal user secret
    envFrom:
      - secretRef:
          name: temporal-sql-secrets

    # Run Temporal with SQL (Postgres) persistence
    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres
            dsn: ${SQL_DEFAULT_DSN}
            maxConns: 20
            maxConnLifetime: 1h
        visibility:
          driver: sql
          sql:
            driver: postgres
            dsn: ${SQL_VISIBILITY_DSN}
            maxConns: 20
            maxConnLifetime: 1h

  # Schema jobs for Postgres (DBs created by admin DSN)
  schema:
    createDatabase:
      enabled: true
      envFrom:
        - secretRef:
            name: temporal-sql-secrets-admin
    setup:
      enabled: true
      envFrom:
        - secretRef:
            name: temporal-sql-secrets
    update:
      enabled: true
      envFrom:
        - secretRef:
            name: temporal-sql-secrets

  web:
    enabled: true
    replicaCount: 2
    service:
      type: ClusterIP

# --- Prometheus / Grafana wrappers (if this stack also deploys them) ---
prometheus:
  enabled: true
  # Optional: node-exporter scheduling (avoid Fargate only nodes)
  nodeExporter:
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - operator: "Exists"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: eks.amazonaws.com/compute-type
                  operator: NotIn
                  values: ["fargate"]
                - key: kubernetes.io/os
                  operator: In
                  values: ["linux"]

grafana:
  enabled: false
