temporal:
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false

  server:
    image:
      repository: temporalio/server
      tag: "1.28.1"

    extraArgs:
      - --allow-no-auth

    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            existingSecret: temporal-sql-secrets   # key: password
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            existingSecret: temporal-sql-secrets   # key: password

    # (optional) TLS mounts if you use them later
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    schema:
      #  THIS is the main kill switch
      enabled: false

      image:
        repository: temporalio/admin-tools
        tag: "1.28"

      # Keep all sub-jobs off too (belt & suspenders)
      createDatabase: { enabled: false }
      setup:          { enabled: false }
      update:         { enabled: false }

      # Optional: if you don’t want the ns job either, set to false
      createNamespace:
        enabled: false
        namespace: default
        retention: 7d

#  Monitoring toggles MUST be top-level (siblings of `temporal`)
grafana:
  enabled: false

prometheus:
  enabled: false
  server:          { enabled: false }
  alertmanager:    { enabled: false }
  pushgateway:     { enabled: false }
  kubeStateMetrics:{ enabled: false }
  nodeExporter:    { enabled: false }
