# Cassandra/ES disable
cassandra:
  enabled: false

elasticsearch:
  enabled: false

# Temporal server uses SQL (Postgres)
server:
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres"

# Run Postgres schema jobs, wire secrets
schema:
  createDatabase:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets-admin
  setup:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets
  update:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets

# already added earlier (keep as-is)
prometheus:
  nodeExporter:
    tolerations:
      - operator: "Exists"
    nodeSelector:
      eks.amazonaws.com/compute-type: ec2
