# ---------- TURN OFF BACKENDS YOU DON'T USE ----------
cassandra:
  enabled: false

elasticsearch:
  enabled: false

mysql:
  enabled: false

# ---------- TEMPORAL SERVER (Postgres via CNPG) ----------
server:
  replicas:
    frontend: 2
    history: 2
    matching: 2
    worker: 2

  image:
    repository: temporalio/server
    tag: "1.28.1"
    pullPolicy: IfNotPresent

  config:
    logLevel: info
    numHistoryShards: 512
    persistence:
      default:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-pg-rw.postgres-temporal.svc
          port: 5432
          database: temporal
          existingSecret: temporal-ha-default-store
          userKey: username
          passwordKey: password

      visibility:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-pg-rw.postgres-temporal.svc
          port: 5432
          database: temporal_visibility
          existingSecret: temporal-ha-visibility-store
          userKey: username
          passwordKey: password

# ---------- SCHEMA JOBS ----------
schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
    backoffLimit: 100
  update:
    enabled: true
    backoffLimit: 100
  # bump this ONLY when you see "Job ... field is immutable"
  jobNameSuffix: "-recreate2"

# ---------- MONITORING ----------
prometheus:
  enabled: true
  server:
    replicaCount: 1
    persistentVolume:
      enabled: true
      # pin to the bound PVC so Helm/Argo never tries to mutate spec
      existingClaim: temporal-ha-dev1-prometheus-server
      size: 8Gi        # ignored when existingClaim is set
  pushgateway:
    enabled: true
  nodeExporter:
    enabled: false     # avoids scheduling noise
  kubeStateMetrics:
    enabled: true
