temporal:
  # hard-disable non-SQL backends
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false
  mysql:
    enabled: false

  server:
    # SQL persistence using env DSNs from secret (already created)
    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            dsn: ${SQL_DEFAULT_DSN}
            maxConns: 20
            maxConnLifetime: 1h
        visibility:
          driver: sql
          sql:
            driver: postgres12
            dsn: ${SQL_VISIBILITY_DSN}
            maxConns: 20
            maxConnLifetime: 1h

    # Always start the server process and point to the mounted config file
    command: ["temporal-server"]
    args:
      - start
      - --config
      - /etc/temporal/config/config_template.yaml

    additionalEnv:
      # Don't pass --env. Just ensure absolute config dir is set.
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config
      - name: SQL_DEFAULT_DSN
        valueFrom:
          secretKeyRef:
            name: temporal-sql-secrets
            key: default.sql.dsn
      - name: SQL_VISIBILITY_DSN
        valueFrom:
          secretKeyRef:
            name: temporal-sql-secrets
            key: visibility.sql.dsn

  # Pin each service similarly (charts that split Deployments will use these)
  frontend:
    command: ["temporal-server"]
    args: ["start","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  history:
    command: ["temporal-server"]
    args: ["start","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  matching:
    command: ["temporal-server"]
    args: ["start","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  worker:
    command: ["temporal-server"]
    args: ["start","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

prometheus:
  nodeExporter:
    enabled: false
