temporal:
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false

  server:
    image:
      repository: temporalio/server
      tag: "1.28.1"

    extraArgs:
      - --allow-no-auth

    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            existingSecret: temporal-sql-secrets   # key: password
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            existingSecret: temporal-sql-secrets   # key: password

    # optional TLS mounts (ok to leave as-is / remove)
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    schema:
      #  schema runner ON, but DB create OFF
      enabled: true

      image:
        repository: temporalio/admin-tools
        tag: "1.28"

      createDatabase:
        enabled: false     
      setup:
        enabled: true         
      update:
        enabled: true         

      # optional: Helm se namespace banana ho to ON; warna tctl se kar lena
      createNamespace:
        enabled: true
        namespace: default
        retention: 7d

# Monitoring stack OFF (clean slate)
grafana:
  enabled: false

prometheus:
  enabled: false
  server:           { enabled: false }
  alertmanager:     { enabled: false }
  pushgateway:      { enabled: false }
  kubeStateMetrics: { enabled: false }
  nodeExporter:     { enabled: false }
