temporal:
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false

  server:
    # Keep server at a real tag you already use successfully
    image:
      repository: temporalio/server
      tag: "1.28.1"

    # Silence the auth warning seen in logs
    extraArgs:
      - --allow-no-auth

    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            existingSecret: temporal-sql-secrets     # reads key "password"
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            existingSecret: temporal-sql-secrets

    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    # --- Schema Jobs (run by Argo CD hooks) ---
    schema:
      # Image/tag that actually exists (avoid 1.28.0 which 404s)
      image:
        repository: temporalio/admin-tools
        tag: "1.28"

      setup:
        enabled: true
        # If you store DSNs in a secret (recommended for schema jobs),
        # provide *both* default and visibility DSNs:
        datastores:
          default:
            existingSecret: temporal-sql-secrets-admin
            existingSecretKey: default.sql.dsn
          visibility:
            existingSecret: temporal-sql-secrets-admin
            existingSecretKey: visibility.sql.dsn
        annotations:
          argocd.argoproj.io/hook: PreSync
          # Keep failed jobs for debugging; recreate on next sync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed
          argocd.argoproj.io/sync-wave: "-1"

      update:
        enabled: true
        datastores:
          default:
            existingSecret: temporal-sql-secrets-admin
            existingSecretKey: default.sql.dsn
          visibility:
            existingSecret: temporal-sql-secrets-admin
            existingSecretKey: visibility.sql.dsn
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed
          argocd.argoproj.io/sync-wave: "-1"

      # (Optional) auto-create a default namespace after schema is ready
      createNamespace:
        enabled: true
        namespace: default
        retention: 7d
