temporal:
  # hard-disable non-sql stores
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false
  mysql:
    enabled: false

  # ---- SQL persistence (Postgres via CNPG) ----
  server:
    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            dsn: ${SQL_DEFAULT_DSN}
            maxConns: 20
            maxConnLifetime: 1h
        visibility:
          driver: sql
          sql:
            driver: postgres12
            dsn: ${SQL_VISIBILITY_DSN}
            maxConns: 20
            maxConnLifetime: 1h

    # IMPORTANT: tell binaries to use the mounted config file (the chart mounts config_template.yaml)
    additionalArgs:
      - --env
      - kubernetes
      - --config
      - /etc/temporal/config/config_template.yaml

    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config
      - name: SQL_DEFAULT_DSN
        valueFrom:
          secretKeyRef:
            name: temporal-sql-secrets
            key: default.sql.dsn
      - name: SQL_VISIBILITY_DSN
        valueFrom:
          secretKeyRef:
            name: temporal-sql-secrets
            key: visibility.sql.dsn

  # also push the same flags/env to each service (belt & suspenders)
  frontend:
    additionalArgs: ["--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  history:
    additionalArgs: ["--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  matching:
    additionalArgs: ["--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

  worker:
    additionalArgs: ["--env","kubernetes","--config","/etc/temporal/config/config_template.yaml"]
    additionalEnv:
      - name: TEMPORAL_ENV
        value: kubernetes
      - name: TEMPORAL_CONFIG_DIR
        value: /etc/temporal/config

prometheus:
  nodeExporter:
    enabled: false
