temporal:
  server:
    image:
      tag: "1.28.1"
    extraArgs:
      - "--allow-no-auth"
    config:
      persistence:
        defaultStore: sql
        numHistoryShards: 4
      # FIX: namespaces must be a map with {create, namespace: []}
      namespaces:
        create: true
        namespace:
          - name: default
            retention: 7d

    # (Keep your SQL wiring as-is)
    sql:
      driver: postgres
      user: "${POSTGRES_USER}"
      password: "${POSTGRES_PWD}"
      host: "temporal-pg-rw.postgres-temporal.svc.cluster.local"
      port: 5432
      database: "temporal"
      ssl:
        enabled: false
      visibility:
        user: "${POSTGRES_USER}"
        password: "${POSTGRES_PWD}"
        host: "temporal-pg-rw.postgres-temporal.svc.cluster.local"
        port: 5432
        database: "temporal_visibility"
        ssl:
          enabled: false

    additionalEnv:
      - name: SQL_MAX_IDLE_CONNS
        value: "50"
      - name: SQL_MAX_OPEN_CONNS
        value: "200"
      - name: SQL_CONN_MAX_LIFETIME
        value: "1h"

  # first sync only — run DB migrations
  schema:
    createDatabase:
      enabled: true    # <<< bootstrap: ON
    setup:
      enabled: true
    update:
      enabled: true

  envFrom:
    - secretRef:
        name: temporal-sql-secrets

  history:
    replicaCount: 1
  matching:
    replicaCount: 1
  frontend:
    replicaCount: 1
  worker:
    replicaCount: 1
