cassandra:
  enabled: false

elasticsearch:
  enabled: false

server:
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres"

schema:
  createDatabase:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets-admin
  setup:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets
  update:
    enabled: true
    envFrom:
      - secretRef:
          name: temporal-sql-secrets

prometheus:
  nodeExporter:
    tolerations:
      - operator: "Exists"
