# ---------- TURN OFF BACKENDS YOU DON'T USE ----------
cassandra:
  enabled: false

elasticsearch:
  enabled: false

mysql:
  enabled: false

# ---------- TEMPORAL SERVER (Postgres via CNPG) ----------
server:
  replicas:
    frontend: 2
    history: 2
    matching: 2
    worker: 2

  image:
    repository: temporalio/server
    tag: "1.28.1"
    pullPolicy: IfNotPresent

  config:
    logLevel: info
    numHistoryShards: 512
    persistence:
      default:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-pg-rw.postgres-temporal.svc
          port: 5432
          database: temporal
          existingSecret: temporal-ha-dev1-default-store   # <-- fix: add dev1
          userKey: username
          passwordKey: password
      visibility:
        driver: sql
        sql:
          driver: postgres12
          host: temporal-pg-rw.postgres-temporal.svc
          port: 5432
          database: temporal_visibility
          existingSecret: temporal-ha-dev1-visibility-store  # <-- fix: add dev1
          userKey: username
          passwordKey: password

# ---------- WEB ----------
web:
  enabled: true
  replicaCount: 1
  image:
    repository: temporalio/ui
    tag: "2.39.0"
    pullPolicy: IfNotPresent

# ---------- SCHEMA JOBS (avoid immutable patch) ----------
schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
    backoffLimit: 100
  update:
    enabled: true
    backoffLimit: 100
  jobNameSuffix: "-recreate1"

# ---------- MONITORING (bind to the existing PVC) ----------
prometheus:
  enabled: true
  server:
    replicaCount: 1
    persistentVolume:
      enabled: true
      existingClaim: temporal-ha-dev1-prometheus-server
  pushgateway:
    enabled: true
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: true
