temporal:
  cassandra:
    enabled: false

  elasticsearch:
    enabled: false

  server:
    image:
      repository: temporalio/server
      tag: "1.28.1"

    # Optional: silence auth warning in dev
    extraArgs:
      - --allow-no-auth

    config:
      persistence:
        default:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal
            user: temporal
            # Secret must contain key: password
            existingSecret: temporal-sql-secrets
        visibility:
          driver: sql
          sql:
            driver: postgres12
            host: temporal-pg-rw.postgres-temporal.svc.cluster.local
            port: 5432
            database: temporal_visibility
            user: temporal
            # Secret must contain key: password
            existingSecret: temporal-sql-secrets

    # Optional (only if you later enable TLS to Postgres)
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    schema:
      image:
        repository: temporalio/admin-tools
        tag: "1.28"

      # Disable all built-in schema jobs (DBs already created/migrated)
      createDatabase:
        enabled: false
      setup:
        enabled: false
      update:
        enabled: false

      # Keep namespace creation (creates 'default' if missing)
      createNamespace:
        enabled: true
        namespace: default
        retention: 7d
