# temporal/charts/temporal-stack/values.yaml

temporal:
  # --- Disable Cassandra & Elasticsearch completely ---
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false

  server:
    # --- Temporal uses SQL(Postgres) for default & visibility stores ---
    config:
      persistence:
        default:
          driver: sql
          sql:
            pluginName: postgres
            # DSN is read from a Secret
            existingSecret: temporal-sql-secrets
            existingSecretKey: default.sql.dsn
        visibility:
          driver: sql
          sql:
            pluginName: postgres
            existingSecret: temporal-sql-secrets
            existingSecretKey: visibility.sql.dsn

    # --- Mount CNPG CA so sslmode=verify-full works from DSN ---
    extraVolumes:
      - name: pg-ca
        secret:
          secretName: temporal-pg-ca        # already present in postgres-temporal; copy/create in `temporal` ns if needed
    extraVolumeMounts:
      - name: pg-ca
        mountPath: /var/run/temporal/pg
        readOnly: true

    # --- Schema Jobs (admin DSN) as Argo hooks (immutable-safe) ---
    schema:
      setup:
        enabled: true
        existingSecret: temporal-sql-secrets-admin
        existingSecretKey: default.sql.dsn
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
          argocd.argoproj.io/sync-wave: "-1"
      update:
        enabled: true
        existingSecret: temporal-sql-secrets-admin
        existingSecretKey: default.sql.dsn
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
          argocd.argoproj.io/sync-wave: "-1"
