apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-temporal-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-temporal
  sources:
    # Source 1: the external Helm chart
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql-ha
      targetRevision: 14.2.28
      helm:
        valueFiles:
          - $values/postgres-temporal-dev.values.yaml
    # Source 2: your repo containing the values file
    - repoURL: https://github.com/Pradeepbisht1/temporal-gitops-demo.git
      targetRevision: HEAD
      path: k8s/values
      ref: values
  syncPolicy:
    automated: {}
